### ISSUE TITLE
Add .gitignore to template to avoid accidentally comitting .env and node_modules

### ISSUE THREAD

**Issue by Joshuafolorunsho** [modelcontextprotocol/create-typescript-server#9]
I can open a PR for this if you guys don't mind.

<img width="1007" alt="image" src="https://github.com/user-attachments/assets/a68cba42-76e6-4816-af86-0c87b7d2f72d">

**Comment by jspahrsummers** [comment]
Sorry for the trouble! We believe we fixed this in https://github.com/modelcontextprotocol/create-typescript-server/pull/8, released in 0.3.1—can you confirm that version works for you?

**Comment by Joshuafolorunsho** [comment]
It works now! Thanks!
